baseURL = 'https://textneckdeveloper.site/'
languageCode = 'en-us'
title = 'textneckdeveloper portfolio'
theme = "hugo-blog-awesome"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[params]
  mainSections = ["posts"]